/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.simon.demo.loginservice.api;

import com.simon.demo.loginservice.model.LoginDTO;
import com.simon.demo.loginservice.model.ProfileDTO;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-26T10:37:30.070+08:00")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "login", nickname = "loginPost", notes = "login", response = ProfileDTO.class, tags={ "Login", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProfileDTO.class) })
    @RequestMapping(value = "/login",
        method = RequestMethod.POST)
    ResponseEntity<ProfileDTO> loginPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody LoginDTO loginDTO);

}
