/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * JiFenBangItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class JiFenBangItem {
  @SerializedName("c1")
  private String c1 = null;

  @SerializedName("c2")
  private String c2 = null;

  @SerializedName("c2L")
  private String c2L = null;

  @SerializedName("c3")
  private String c3 = null;

  @SerializedName("c41")
  private String c41 = null;

  @SerializedName("c42")
  private String c42 = null;

  @SerializedName("c43")
  private String c43 = null;

  @SerializedName("c5")
  private String c5 = null;

  @SerializedName("c6")
  private String c6 = null;

  public JiFenBangItem c1(String c1) {
    this.c1 = c1;
    return this;
  }

   /**
   * Get c1
   * @return c1
  **/
  @ApiModelProperty(value = "")
  public String getC1() {
    return c1;
  }

  public void setC1(String c1) {
    this.c1 = c1;
  }

  public JiFenBangItem c2(String c2) {
    this.c2 = c2;
    return this;
  }

   /**
   * Get c2
   * @return c2
  **/
  @ApiModelProperty(value = "")
  public String getC2() {
    return c2;
  }

  public void setC2(String c2) {
    this.c2 = c2;
  }

  public JiFenBangItem c2L(String c2L) {
    this.c2L = c2L;
    return this;
  }

   /**
   * Get c2L
   * @return c2L
  **/
  @ApiModelProperty(value = "")
  public String getC2L() {
    return c2L;
  }

  public void setC2L(String c2L) {
    this.c2L = c2L;
  }

  public JiFenBangItem c3(String c3) {
    this.c3 = c3;
    return this;
  }

   /**
   * Get c3
   * @return c3
  **/
  @ApiModelProperty(value = "")
  public String getC3() {
    return c3;
  }

  public void setC3(String c3) {
    this.c3 = c3;
  }

  public JiFenBangItem c41(String c41) {
    this.c41 = c41;
    return this;
  }

   /**
   * Get c41
   * @return c41
  **/
  @ApiModelProperty(value = "")
  public String getC41() {
    return c41;
  }

  public void setC41(String c41) {
    this.c41 = c41;
  }

  public JiFenBangItem c42(String c42) {
    this.c42 = c42;
    return this;
  }

   /**
   * Get c42
   * @return c42
  **/
  @ApiModelProperty(value = "")
  public String getC42() {
    return c42;
  }

  public void setC42(String c42) {
    this.c42 = c42;
  }

  public JiFenBangItem c43(String c43) {
    this.c43 = c43;
    return this;
  }

   /**
   * Get c43
   * @return c43
  **/
  @ApiModelProperty(value = "")
  public String getC43() {
    return c43;
  }

  public void setC43(String c43) {
    this.c43 = c43;
  }

  public JiFenBangItem c5(String c5) {
    this.c5 = c5;
    return this;
  }

   /**
   * Get c5
   * @return c5
  **/
  @ApiModelProperty(value = "")
  public String getC5() {
    return c5;
  }

  public void setC5(String c5) {
    this.c5 = c5;
  }

  public JiFenBangItem c6(String c6) {
    this.c6 = c6;
    return this;
  }

   /**
   * Get c6
   * @return c6
  **/
  @ApiModelProperty(value = "")
  public String getC6() {
    return c6;
  }

  public void setC6(String c6) {
    this.c6 = c6;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JiFenBangItem jiFenBangItem = (JiFenBangItem) o;
    return Objects.equals(this.c1, jiFenBangItem.c1) &&
        Objects.equals(this.c2, jiFenBangItem.c2) &&
        Objects.equals(this.c2L, jiFenBangItem.c2L) &&
        Objects.equals(this.c3, jiFenBangItem.c3) &&
        Objects.equals(this.c41, jiFenBangItem.c41) &&
        Objects.equals(this.c42, jiFenBangItem.c42) &&
        Objects.equals(this.c43, jiFenBangItem.c43) &&
        Objects.equals(this.c5, jiFenBangItem.c5) &&
        Objects.equals(this.c6, jiFenBangItem.c6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(c1, c2, c2L, c3, c41, c42, c43, c5, c6);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JiFenBangItem {\n");
    
    sb.append("    c1: ").append(toIndentedString(c1)).append("\n");
    sb.append("    c2: ").append(toIndentedString(c2)).append("\n");
    sb.append("    c2L: ").append(toIndentedString(c2L)).append("\n");
    sb.append("    c3: ").append(toIndentedString(c3)).append("\n");
    sb.append("    c41: ").append(toIndentedString(c41)).append("\n");
    sb.append("    c42: ").append(toIndentedString(c42)).append("\n");
    sb.append("    c43: ").append(toIndentedString(c43)).append("\n");
    sb.append("    c5: ").append(toIndentedString(c5)).append("\n");
    sb.append("    c6: ").append(toIndentedString(c6)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

