/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SaiChengDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class SaiChengDTO {
  @SerializedName("reason")
  private String reason = null;

  @SerializedName("result")
  private SaiChengDTOResult result = null;

  @SerializedName("error_code")
  private Integer errorCode = null;

  public SaiChengDTO reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public SaiChengDTO result(SaiChengDTOResult result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public SaiChengDTOResult getResult() {
    return result;
  }

  public void setResult(SaiChengDTOResult result) {
    this.result = result;
  }

  public SaiChengDTO errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(value = "")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaiChengDTO saiChengDTO = (SaiChengDTO) o;
    return Objects.equals(this.reason, saiChengDTO.reason) &&
        Objects.equals(this.result, saiChengDTO.result) &&
        Objects.equals(this.errorCode, saiChengDTO.errorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, result, errorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaiChengDTO {\n");
    
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

