/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SaiChengDTOResultViews
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class SaiChengDTOResultViews {
  @SerializedName("saicheng1")
  private List<SaiChengItem> saicheng1 = null;

  @SerializedName("saicheng2")
  private List<SaiChengItem> saicheng2 = null;

  @SerializedName("saicheng3")
  private List<SaiChengItem> saicheng3 = null;

  @SerializedName("jifenbang")
  private List<JiFenBangItem> jifenbang = null;

  @SerializedName("sheshoubang")
  private List<SheShouBangItem> sheshoubang = null;

  public SaiChengDTOResultViews saicheng1(List<SaiChengItem> saicheng1) {
    this.saicheng1 = saicheng1;
    return this;
  }

  public SaiChengDTOResultViews addSaicheng1Item(SaiChengItem saicheng1Item) {
    if (this.saicheng1 == null) {
      this.saicheng1 = new ArrayList<SaiChengItem>();
    }
    this.saicheng1.add(saicheng1Item);
    return this;
  }

   /**
   * Get saicheng1
   * @return saicheng1
  **/
  @ApiModelProperty(value = "")
  public List<SaiChengItem> getSaicheng1() {
    return saicheng1;
  }

  public void setSaicheng1(List<SaiChengItem> saicheng1) {
    this.saicheng1 = saicheng1;
  }

  public SaiChengDTOResultViews saicheng2(List<SaiChengItem> saicheng2) {
    this.saicheng2 = saicheng2;
    return this;
  }

  public SaiChengDTOResultViews addSaicheng2Item(SaiChengItem saicheng2Item) {
    if (this.saicheng2 == null) {
      this.saicheng2 = new ArrayList<SaiChengItem>();
    }
    this.saicheng2.add(saicheng2Item);
    return this;
  }

   /**
   * Get saicheng2
   * @return saicheng2
  **/
  @ApiModelProperty(value = "")
  public List<SaiChengItem> getSaicheng2() {
    return saicheng2;
  }

  public void setSaicheng2(List<SaiChengItem> saicheng2) {
    this.saicheng2 = saicheng2;
  }

  public SaiChengDTOResultViews saicheng3(List<SaiChengItem> saicheng3) {
    this.saicheng3 = saicheng3;
    return this;
  }

  public SaiChengDTOResultViews addSaicheng3Item(SaiChengItem saicheng3Item) {
    if (this.saicheng3 == null) {
      this.saicheng3 = new ArrayList<SaiChengItem>();
    }
    this.saicheng3.add(saicheng3Item);
    return this;
  }

   /**
   * Get saicheng3
   * @return saicheng3
  **/
  @ApiModelProperty(value = "")
  public List<SaiChengItem> getSaicheng3() {
    return saicheng3;
  }

  public void setSaicheng3(List<SaiChengItem> saicheng3) {
    this.saicheng3 = saicheng3;
  }

  public SaiChengDTOResultViews jifenbang(List<JiFenBangItem> jifenbang) {
    this.jifenbang = jifenbang;
    return this;
  }

  public SaiChengDTOResultViews addJifenbangItem(JiFenBangItem jifenbangItem) {
    if (this.jifenbang == null) {
      this.jifenbang = new ArrayList<JiFenBangItem>();
    }
    this.jifenbang.add(jifenbangItem);
    return this;
  }

   /**
   * Get jifenbang
   * @return jifenbang
  **/
  @ApiModelProperty(value = "")
  public List<JiFenBangItem> getJifenbang() {
    return jifenbang;
  }

  public void setJifenbang(List<JiFenBangItem> jifenbang) {
    this.jifenbang = jifenbang;
  }

  public SaiChengDTOResultViews sheshoubang(List<SheShouBangItem> sheshoubang) {
    this.sheshoubang = sheshoubang;
    return this;
  }

  public SaiChengDTOResultViews addSheshoubangItem(SheShouBangItem sheshoubangItem) {
    if (this.sheshoubang == null) {
      this.sheshoubang = new ArrayList<SheShouBangItem>();
    }
    this.sheshoubang.add(sheshoubangItem);
    return this;
  }

   /**
   * Get sheshoubang
   * @return sheshoubang
  **/
  @ApiModelProperty(value = "")
  public List<SheShouBangItem> getSheshoubang() {
    return sheshoubang;
  }

  public void setSheshoubang(List<SheShouBangItem> sheshoubang) {
    this.sheshoubang = sheshoubang;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaiChengDTOResultViews saiChengDTOResultViews = (SaiChengDTOResultViews) o;
    return Objects.equals(this.saicheng1, saiChengDTOResultViews.saicheng1) &&
        Objects.equals(this.saicheng2, saiChengDTOResultViews.saicheng2) &&
        Objects.equals(this.saicheng3, saiChengDTOResultViews.saicheng3) &&
        Objects.equals(this.jifenbang, saiChengDTOResultViews.jifenbang) &&
        Objects.equals(this.sheshoubang, saiChengDTOResultViews.sheshoubang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saicheng1, saicheng2, saicheng3, jifenbang, sheshoubang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaiChengDTOResultViews {\n");
    
    sb.append("    saicheng1: ").append(toIndentedString(saicheng1)).append("\n");
    sb.append("    saicheng2: ").append(toIndentedString(saicheng2)).append("\n");
    sb.append("    saicheng3: ").append(toIndentedString(saicheng3)).append("\n");
    sb.append("    jifenbang: ").append(toIndentedString(jifenbang)).append("\n");
    sb.append("    sheshoubang: ").append(toIndentedString(sheshoubang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

