/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SaiChengItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class SaiChengItem {
  @SerializedName("c1")
  private String c1 = null;

  @SerializedName("c2")
  private String c2 = null;

  @SerializedName("c3")
  private String c3 = null;

  @SerializedName("c4R")
  private String c4R = null;

  @SerializedName("c4T1")
  private String c4T1 = null;

  @SerializedName("c4T1URL")
  private String c4T1URL = null;

  @SerializedName("c4T2")
  private String c4T2 = null;

  @SerializedName("c4T2URL")
  private String c4T2URL = null;

  @SerializedName("c51")
  private String c51 = null;

  @SerializedName("c51Link")
  private String c51Link = null;

  @SerializedName("c52")
  private String c52 = null;

  @SerializedName("c52Link")
  private String c52Link = null;

  public SaiChengItem c1(String c1) {
    this.c1 = c1;
    return this;
  }

   /**
   * Get c1
   * @return c1
  **/
  @ApiModelProperty(value = "")
  public String getC1() {
    return c1;
  }

  public void setC1(String c1) {
    this.c1 = c1;
  }

  public SaiChengItem c2(String c2) {
    this.c2 = c2;
    return this;
  }

   /**
   * Get c2
   * @return c2
  **/
  @ApiModelProperty(value = "")
  public String getC2() {
    return c2;
  }

  public void setC2(String c2) {
    this.c2 = c2;
  }

  public SaiChengItem c3(String c3) {
    this.c3 = c3;
    return this;
  }

   /**
   * Get c3
   * @return c3
  **/
  @ApiModelProperty(value = "")
  public String getC3() {
    return c3;
  }

  public void setC3(String c3) {
    this.c3 = c3;
  }

  public SaiChengItem c4R(String c4R) {
    this.c4R = c4R;
    return this;
  }

   /**
   * Get c4R
   * @return c4R
  **/
  @ApiModelProperty(value = "")
  public String getC4R() {
    return c4R;
  }

  public void setC4R(String c4R) {
    this.c4R = c4R;
  }

  public SaiChengItem c4T1(String c4T1) {
    this.c4T1 = c4T1;
    return this;
  }

   /**
   * Get c4T1
   * @return c4T1
  **/
  @ApiModelProperty(value = "")
  public String getC4T1() {
    return c4T1;
  }

  public void setC4T1(String c4T1) {
    this.c4T1 = c4T1;
  }

  public SaiChengItem c4T1URL(String c4T1URL) {
    this.c4T1URL = c4T1URL;
    return this;
  }

   /**
   * Get c4T1URL
   * @return c4T1URL
  **/
  @ApiModelProperty(value = "")
  public String getC4T1URL() {
    return c4T1URL;
  }

  public void setC4T1URL(String c4T1URL) {
    this.c4T1URL = c4T1URL;
  }

  public SaiChengItem c4T2(String c4T2) {
    this.c4T2 = c4T2;
    return this;
  }

   /**
   * Get c4T2
   * @return c4T2
  **/
  @ApiModelProperty(value = "")
  public String getC4T2() {
    return c4T2;
  }

  public void setC4T2(String c4T2) {
    this.c4T2 = c4T2;
  }

  public SaiChengItem c4T2URL(String c4T2URL) {
    this.c4T2URL = c4T2URL;
    return this;
  }

   /**
   * Get c4T2URL
   * @return c4T2URL
  **/
  @ApiModelProperty(value = "")
  public String getC4T2URL() {
    return c4T2URL;
  }

  public void setC4T2URL(String c4T2URL) {
    this.c4T2URL = c4T2URL;
  }

  public SaiChengItem c51(String c51) {
    this.c51 = c51;
    return this;
  }

   /**
   * Get c51
   * @return c51
  **/
  @ApiModelProperty(value = "")
  public String getC51() {
    return c51;
  }

  public void setC51(String c51) {
    this.c51 = c51;
  }

  public SaiChengItem c51Link(String c51Link) {
    this.c51Link = c51Link;
    return this;
  }

   /**
   * Get c51Link
   * @return c51Link
  **/
  @ApiModelProperty(value = "")
  public String getC51Link() {
    return c51Link;
  }

  public void setC51Link(String c51Link) {
    this.c51Link = c51Link;
  }

  public SaiChengItem c52(String c52) {
    this.c52 = c52;
    return this;
  }

   /**
   * Get c52
   * @return c52
  **/
  @ApiModelProperty(value = "")
  public String getC52() {
    return c52;
  }

  public void setC52(String c52) {
    this.c52 = c52;
  }

  public SaiChengItem c52Link(String c52Link) {
    this.c52Link = c52Link;
    return this;
  }

   /**
   * Get c52Link
   * @return c52Link
  **/
  @ApiModelProperty(value = "")
  public String getC52Link() {
    return c52Link;
  }

  public void setC52Link(String c52Link) {
    this.c52Link = c52Link;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaiChengItem saiChengItem = (SaiChengItem) o;
    return Objects.equals(this.c1, saiChengItem.c1) &&
        Objects.equals(this.c2, saiChengItem.c2) &&
        Objects.equals(this.c3, saiChengItem.c3) &&
        Objects.equals(this.c4R, saiChengItem.c4R) &&
        Objects.equals(this.c4T1, saiChengItem.c4T1) &&
        Objects.equals(this.c4T1URL, saiChengItem.c4T1URL) &&
        Objects.equals(this.c4T2, saiChengItem.c4T2) &&
        Objects.equals(this.c4T2URL, saiChengItem.c4T2URL) &&
        Objects.equals(this.c51, saiChengItem.c51) &&
        Objects.equals(this.c51Link, saiChengItem.c51Link) &&
        Objects.equals(this.c52, saiChengItem.c52) &&
        Objects.equals(this.c52Link, saiChengItem.c52Link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(c1, c2, c3, c4R, c4T1, c4T1URL, c4T2, c4T2URL, c51, c51Link, c52, c52Link);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaiChengItem {\n");
    
    sb.append("    c1: ").append(toIndentedString(c1)).append("\n");
    sb.append("    c2: ").append(toIndentedString(c2)).append("\n");
    sb.append("    c3: ").append(toIndentedString(c3)).append("\n");
    sb.append("    c4R: ").append(toIndentedString(c4R)).append("\n");
    sb.append("    c4T1: ").append(toIndentedString(c4T1)).append("\n");
    sb.append("    c4T1URL: ").append(toIndentedString(c4T1URL)).append("\n");
    sb.append("    c4T2: ").append(toIndentedString(c4T2)).append("\n");
    sb.append("    c4T2URL: ").append(toIndentedString(c4T2URL)).append("\n");
    sb.append("    c51: ").append(toIndentedString(c51)).append("\n");
    sb.append("    c51Link: ").append(toIndentedString(c51Link)).append("\n");
    sb.append("    c52: ").append(toIndentedString(c52)).append("\n");
    sb.append("    c52Link: ").append(toIndentedString(c52Link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

