/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SaiChengDTOResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class SaiChengDTOResult {
  @SerializedName("key")
  private String key = null;

  @SerializedName("tabs")
  private SaiChengDTOResultTabs tabs = null;

  @SerializedName("views")
  private SaiChengDTOResultViews views = null;

  public SaiChengDTOResult key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public SaiChengDTOResult tabs(SaiChengDTOResultTabs tabs) {
    this.tabs = tabs;
    return this;
  }

   /**
   * Get tabs
   * @return tabs
  **/
  @ApiModelProperty(value = "")
  public SaiChengDTOResultTabs getTabs() {
    return tabs;
  }

  public void setTabs(SaiChengDTOResultTabs tabs) {
    this.tabs = tabs;
  }

  public SaiChengDTOResult views(SaiChengDTOResultViews views) {
    this.views = views;
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @ApiModelProperty(value = "")
  public SaiChengDTOResultViews getViews() {
    return views;
  }

  public void setViews(SaiChengDTOResultViews views) {
    this.views = views;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaiChengDTOResult saiChengDTOResult = (SaiChengDTOResult) o;
    return Objects.equals(this.key, saiChengDTOResult.key) &&
        Objects.equals(this.tabs, saiChengDTOResult.tabs) &&
        Objects.equals(this.views, saiChengDTOResult.views);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, tabs, views);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaiChengDTOResult {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    tabs: ").append(toIndentedString(tabs)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

