/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SaiChengDTOResultTabs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class SaiChengDTOResultTabs {
  @SerializedName("saicheng1")
  private String saicheng1 = null;

  @SerializedName("saicheng2")
  private String saicheng2 = null;

  @SerializedName("saicheng3")
  private String saicheng3 = null;

  @SerializedName("jifenbang")
  private String jifenbang = null;

  @SerializedName("sheshoubang")
  private String sheshoubang = null;

  public SaiChengDTOResultTabs saicheng1(String saicheng1) {
    this.saicheng1 = saicheng1;
    return this;
  }

   /**
   * Get saicheng1
   * @return saicheng1
  **/
  @ApiModelProperty(value = "")
  public String getSaicheng1() {
    return saicheng1;
  }

  public void setSaicheng1(String saicheng1) {
    this.saicheng1 = saicheng1;
  }

  public SaiChengDTOResultTabs saicheng2(String saicheng2) {
    this.saicheng2 = saicheng2;
    return this;
  }

   /**
   * Get saicheng2
   * @return saicheng2
  **/
  @ApiModelProperty(value = "")
  public String getSaicheng2() {
    return saicheng2;
  }

  public void setSaicheng2(String saicheng2) {
    this.saicheng2 = saicheng2;
  }

  public SaiChengDTOResultTabs saicheng3(String saicheng3) {
    this.saicheng3 = saicheng3;
    return this;
  }

   /**
   * Get saicheng3
   * @return saicheng3
  **/
  @ApiModelProperty(value = "")
  public String getSaicheng3() {
    return saicheng3;
  }

  public void setSaicheng3(String saicheng3) {
    this.saicheng3 = saicheng3;
  }

  public SaiChengDTOResultTabs jifenbang(String jifenbang) {
    this.jifenbang = jifenbang;
    return this;
  }

   /**
   * Get jifenbang
   * @return jifenbang
  **/
  @ApiModelProperty(value = "")
  public String getJifenbang() {
    return jifenbang;
  }

  public void setJifenbang(String jifenbang) {
    this.jifenbang = jifenbang;
  }

  public SaiChengDTOResultTabs sheshoubang(String sheshoubang) {
    this.sheshoubang = sheshoubang;
    return this;
  }

   /**
   * Get sheshoubang
   * @return sheshoubang
  **/
  @ApiModelProperty(value = "")
  public String getSheshoubang() {
    return sheshoubang;
  }

  public void setSheshoubang(String sheshoubang) {
    this.sheshoubang = sheshoubang;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaiChengDTOResultTabs saiChengDTOResultTabs = (SaiChengDTOResultTabs) o;
    return Objects.equals(this.saicheng1, saiChengDTOResultTabs.saicheng1) &&
        Objects.equals(this.saicheng2, saiChengDTOResultTabs.saicheng2) &&
        Objects.equals(this.saicheng3, saiChengDTOResultTabs.saicheng3) &&
        Objects.equals(this.jifenbang, saiChengDTOResultTabs.jifenbang) &&
        Objects.equals(this.sheshoubang, saiChengDTOResultTabs.sheshoubang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saicheng1, saicheng2, saicheng3, jifenbang, sheshoubang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaiChengDTOResultTabs {\n");
    
    sb.append("    saicheng1: ").append(toIndentedString(saicheng1)).append("\n");
    sb.append("    saicheng2: ").append(toIndentedString(saicheng2)).append("\n");
    sb.append("    saicheng3: ").append(toIndentedString(saicheng3)).append("\n");
    sb.append("    jifenbang: ").append(toIndentedString(jifenbang)).append("\n");
    sb.append("    sheshoubang: ").append(toIndentedString(sheshoubang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

