/*
 * Soccer
 * description
 *
 * OpenAPI spec version: 0.0.0
 * Contact: 243120877@qq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.simon.wx.soccer.model.liansai;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SheShouBangItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-12T02:34:09.022Z")
public class SheShouBangItem {
  @SerializedName("c1")
  private String c1 = null;

  @SerializedName("c2")
  private String c2 = null;

  @SerializedName("c2L")
  private String c2L = null;

  @SerializedName("c3")
  private String c3 = null;

  @SerializedName("c3L")
  private String c3L = null;

  @SerializedName("c4")
  private String c4 = null;

  @SerializedName("c5")
  private String c5 = null;

  public SheShouBangItem c1(String c1) {
    this.c1 = c1;
    return this;
  }

   /**
   * Get c1
   * @return c1
  **/
  @ApiModelProperty(value = "")
  public String getC1() {
    return c1;
  }

  public void setC1(String c1) {
    this.c1 = c1;
  }

  public SheShouBangItem c2(String c2) {
    this.c2 = c2;
    return this;
  }

   /**
   * Get c2
   * @return c2
  **/
  @ApiModelProperty(value = "")
  public String getC2() {
    return c2;
  }

  public void setC2(String c2) {
    this.c2 = c2;
  }

  public SheShouBangItem c2L(String c2L) {
    this.c2L = c2L;
    return this;
  }

   /**
   * Get c2L
   * @return c2L
  **/
  @ApiModelProperty(value = "")
  public String getC2L() {
    return c2L;
  }

  public void setC2L(String c2L) {
    this.c2L = c2L;
  }

  public SheShouBangItem c3(String c3) {
    this.c3 = c3;
    return this;
  }

   /**
   * Get c3
   * @return c3
  **/
  @ApiModelProperty(value = "")
  public String getC3() {
    return c3;
  }

  public void setC3(String c3) {
    this.c3 = c3;
  }

  public SheShouBangItem c3L(String c3L) {
    this.c3L = c3L;
    return this;
  }

   /**
   * Get c3L
   * @return c3L
  **/
  @ApiModelProperty(value = "")
  public String getC3L() {
    return c3L;
  }

  public void setC3L(String c3L) {
    this.c3L = c3L;
  }

  public SheShouBangItem c4(String c4) {
    this.c4 = c4;
    return this;
  }

   /**
   * Get c4
   * @return c4
  **/
  @ApiModelProperty(value = "")
  public String getC4() {
    return c4;
  }

  public void setC4(String c4) {
    this.c4 = c4;
  }

  public SheShouBangItem c5(String c5) {
    this.c5 = c5;
    return this;
  }

   /**
   * Get c5
   * @return c5
  **/
  @ApiModelProperty(value = "")
  public String getC5() {
    return c5;
  }

  public void setC5(String c5) {
    this.c5 = c5;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SheShouBangItem sheShouBangItem = (SheShouBangItem) o;
    return Objects.equals(this.c1, sheShouBangItem.c1) &&
        Objects.equals(this.c2, sheShouBangItem.c2) &&
        Objects.equals(this.c2L, sheShouBangItem.c2L) &&
        Objects.equals(this.c3, sheShouBangItem.c3) &&
        Objects.equals(this.c3L, sheShouBangItem.c3L) &&
        Objects.equals(this.c4, sheShouBangItem.c4) &&
        Objects.equals(this.c5, sheShouBangItem.c5);
  }

  @Override
  public int hashCode() {
    return Objects.hash(c1, c2, c2L, c3, c3L, c4, c5);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SheShouBangItem {\n");
    
    sb.append("    c1: ").append(toIndentedString(c1)).append("\n");
    sb.append("    c2: ").append(toIndentedString(c2)).append("\n");
    sb.append("    c2L: ").append(toIndentedString(c2L)).append("\n");
    sb.append("    c3: ").append(toIndentedString(c3)).append("\n");
    sb.append("    c3L: ").append(toIndentedString(c3L)).append("\n");
    sb.append("    c4: ").append(toIndentedString(c4)).append("\n");
    sb.append("    c5: ").append(toIndentedString(c5)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

