server:
  port: 18090
spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/profile_schema?useSSL=false
    username: profile_dba
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/