eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 17000

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: 18000