server:
  port: 18080
  servlet:
    context-path: /login-service

spring:
  application:
    name: login-service
  cloud:
    loadbalancer:
      retry:
        enabled: true

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

profile-service:
  ribbon:
    MaxAutoRetries: 100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/