server:
  port: 18080
  servlet:
    context-path: /login-service

spring:
  application:
    name: login-service

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:18000/eureka/